export const toyota = [
  {
    img: './images/carmodels/toyota/toyota9.webp',
    price: 'STARTING FROM 65.2 LAKHS',
    model: 'Toyota Land Cruiser Prado',
    pricecount: '₹ 31,000,000',
    mileage: '11.3 km/L',
    variant: 'Diesel',
    engineCc: '2982 cc',
    torque: '420Nm',
    power: '173 bhp',
    seatingCapacity: '7',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Toyota/Toyota-Fortuner/1634879216/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Toyota/Toyota-Fortuner/1616818166/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/carmodels/toyota/toyota8.webp',
    price: 'STARTING FROM 20.5 LAKHS',
    model: 'Toyota Corolla Altis',
    pricecount: '₹ 15,000,000',
    mileage: '16.7 km/L',
    variant: 'Petrol',
    engineCc: '1798 cc',
    torque: '142Nm',
    power: '138 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Toyota/Toyota-Fortuner/1634879216/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Toyota/Toyota-Fortuner/1616818166/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/carmodels/toyota/toyota7.webp',
    price: 'STARTING FROM 10.8 LAKHS',
    model: 'Toyota Yaris',
    pricecount: '₹ 9,000,000',
    mileage: '17.1 km/L',
    variant: 'Petrol',
    engineCc: '1496 cc',
    torque: '140Nm',
    power: '105 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Toyota/Toyota-Fortuner/1634879216/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Toyota/Toyota-Fortuner/1616818166/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/carmodels/toyota/toyota6.webp',
    price: 'STARTING FROM 90.2 LAKHS',
    model: 'Toyota Vellfire',
    pricecount: '₹ 45,000,000',
    mileage: '16.3 km/L',
    variant: 'Hybrid',
    engineCc: '2494 cc',
    torque: '198Nm',
    power: '86 bhp',
    seatingCapacity: '7',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Toyota/Toyota-Fortuner/1634879216/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Toyota/Toyota-Fortuner/1616818166/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/carmodels/toyota/toyota5.webp',
    price: 'STARTING FROM 8.5 LAKHS',
    model: 'Toyota Urban Cruiser',
    pricecount: '₹ 7,000,000',
    mileage: '18.76 km/L',
    variant: 'Petrol',
    engineCc: '1462 cc',
    torque: '138Nm',
    power: '103 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Toyota/Toyota-Fortuner/1634879216/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Toyota/Toyota-Fortuner/1616818166/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/carmodels/toyota/toyota4.webp',
    price: 'STARTING FROM 40.9 LAKHS',
    model: 'Toyota Camry',
    pricecount: '₹ 35,000,000',
    mileage: '19.16 km/L',
    variant: 'Hybrid',
    engineCc: '2487 cc',
    torque: '221Nm',
    power: '175 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Toyota/Toyota-Fortuner/1634879216/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Toyota/Toyota-Fortuner/1616818166/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/carmodels/toyota/toyota3.webp',
    price: 'STARTING FROM 7.8 LAKHS',
    model: 'Toyota Glanza',
    pricecount: '₹ 6,000,000',
    mileage: '21.01 km/L',
    variant: 'Petrol',
    engineCc: '1197 cc',
    torque: '113Nm',
    power: '82 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Toyota/Toyota-Fortuner/1634879216/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Toyota/Toyota-Fortuner/1616818166/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/carmodels/toyota/toyota2.webp',
    price: 'STARTING FROM 16.3 LAKHS',
    model: 'Toyota Innova Crysta',
    pricecount: '₹ 13,000,000',
    mileage: '13.68 km/L',
    variant: 'Diesel',
    engineCc: '2393 cc',
    torque: '360Nm',
    power: '148 bhp',
    seatingCapacity: '7/8',
    Drivetype: 'RWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Toyota/Toyota-Fortuner/1634879216/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Toyota/Toyota-Fortuner/1616818166/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/carmodels/toyota/toyota1.webp',
    price: 'STARTING FROM 33.5 LAKHS',
    model: 'Toyota Fortuner',
    pricecount: '₹ 30,000,000',
    mileage: '12.8 km/L',
    variant: 'Diesel',
    engineCc: '2755 cc',
    torque: '500Nm',
    power: '174 bhp',
    seatingCapacity: '7',
    Drivetype: 'AWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Toyota/Toyota-Fortuner/1634879216/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Toyota/Toyota-Fortuner/1616818166/Exterior.html?hotSpotNonApp=yes'
  }
];


export const benz = [
  {
    img: './images/seperate/benz/benz1.webp',
    price: 'STARTING FROM 50.2 LAKHS',
    model: 'Mercedes-Benz A-Class',
    pricecount: '₹ 23,000,000',
    mileage: '21.4 km/L',
    variant: 'Petrol',
    engineCc: '1197 cc',
    torque: '113Nm',
    power: '82 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: '',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mercedes-Benz/Mercedes-Benz-A-Class-Limousine/Exterior.html?hotSpotNonApp=yes'
  }
,
  {
    img: './images/seperate/benz/benz2.webp',
    price: 'STARTING FROM 60.5 LAKHS',
    model: 'Mercedes-Benz C-Class',
    pricecount: '₹ 25,000,000',
    mileage: '20.8 km/L',
    variant: 'Petrol',
    engineCc: '1991 cc',
    torque: '320Nm',
    power: '201 bhp',
    seatingCapacity: '5',
    Drivetype: 'RWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/c-class/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mercedes-Benz/Mercedes-Benz-A-Class-Limousine/Exterior.html?hotSpotNonApp=yes'
  }
,
  {
    img: './images/seperate/benz/benz4.webp',
    price: 'STARTING FROM 75.8 LAKHS',
    model: 'Mercedes-Benz GLE',
    pricecount: '₹ 30,000,000',
    mileage: '19.5 km/L',
    variant: 'Diesel',
    engineCc: '2925 cc',
    torque: '700Nm',
    power: '325 bhp',
    seatingCapacity: '7',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/gle/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mercedes-Benz/Mercedes-Benz-GLE/1692872134/Exterior.html?hotSpotNonApp=yes'
  }
,
  {
    img: './images/seperate/benz/benz4.webp',
    price: 'STARTING FROM 40.2 LAKHS',
    model: 'Mercedes-Benz GLA',
    pricecount: '₹ 20,000,000',
    mileage: '18.9 km/L',
    variant: 'Petrol',
    engineCc: '1991 cc',
    torque: '300Nm',
    power: '201 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://example.com/360-view/gla/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mercedes-Benz/Mercedes-Benz-GLA/1692872134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/benz/benz4.webp',
    price: 'STARTING FROM 65.5 LAKHS',
    model: 'Mercedes-Benz E-Class',
    pricecount: '₹ 28,000,000',
    mileage: '20.5 km/L',
    variant: 'Diesel',
    engineCc: '1950 cc',
    torque: '400Nm',
    power: '191 bhp',
    seatingCapacity: '5',
    Drivetype: 'RWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/e-class/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mercedes-Benz/Mercedes-Benz-A-Class-Limousine/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/benz/benz4.webp',
    price: 'STARTING FROM 55.2 LAKHS',
    model: 'Mercedes-Benz GLC',
    pricecount: '₹ 24,000,000',
    mileage: '22.3 km/L',
    variant: 'Petrol',
    engineCc: '1991 cc',
    torque: '350Nm',
    power: '241 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/glc/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mercedes-Benz/Mercedes-Benz-GLC/Exterior.html?hotSpotNonApp=yes'
  },
    {
      img: './images/seperate/benz/benz4.webp',
      price: 'STARTING FROM 50.2 LAKHS',
      model: 'Mercedes-Benz A-Clas',
      pricecount: '₹ 23,000,000',
      mileage: '21.4 km/L',
      variant: 'Petrol',
      engineCc: '1197 cc',
      torque: '113Nm',
      power: '82 bhp',
      seatingCapacity: '5',
      Drivetype: 'FWD',
      NCAPsafetyrating: '4 Star',
      iframeInterior: 'https://example.com/360-view/glanza/interior',
      iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Toyota/Toyota-Glanza/1692872134/Exterior.html?hotSpotNonApp=yes'
    },
    {
      img: './images/seperate/benz/benz4.webp',
      price: 'STARTING FROM 80.2 LAKHS',
      model: 'Mercedes-Benz EQC',
      pricecount: '₹ 35,000,000',
      mileage: '18.6 km/L',
      variant: 'Electric',
      engineCc: 'N/A',
      torque: '760Nm',
      power: '402 bhp',
      seatingCapacity: '5',
      Drivetype: 'AWD',
      NCAPsafetyrating: '5 Star',
      iframeInterior: 'https://example.com/360-view/eqc/interior',
      iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mercedes-Benz/Mercedes-Benz-EQC/1692872134/Exterior.html?hotSpotNonApp=yes'
    },
    {
      img: './images/seperate/benz/benz4.webp',
      price: 'STARTING FROM 130.5 LAKHS',
      model: 'Mercedes-Benz AMG GT',
      pricecount: '₹ 60,000,000',
      mileage: '11.8 km/L',
      variant: 'Petrol',
      engineCc: '3982 cc',
      torque: '700Nm',
      power: '577 bhp',
      seatingCapacity: '2',
      Drivetype: 'RWD',
      NCAPsafetyrating: 'Not Rated',
      iframeInterior: 'https://example.com/360-view/amg-gt/interior',
      iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mercedes-Benz/Mercedes-Benz-AMG-GT/1692872134/Exterior.html?hotSpotNonApp=yes'
    },
    {
      img: './images/seperate/benz/benz4.webp',
      price: 'STARTING FROM 180.2 LAKHS',
      model: 'Mercedes-Benz G-Class',
      pricecount: '₹ 70,000,000',
      mileage: '8.1 km/L',
      variant: 'Petrol',
      engineCc: '3982 cc',
      torque: '850Nm',
      power: '577 bhp',
      seatingCapacity: '5',
      Drivetype: 'AWD',
      NCAPsafetyrating: 'Not Rated',
      iframeInterior: 'https://example.com/360-view/g-class/interior',
      iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mercedes-Benz/Mercedes-Benz-G-Class/1692872134/Exterior.html?hotSpotNonApp=yes'
    },
    {
      img: './images/seperate/benz/benz4.webp',
      price: 'STARTING FROM 70.8 LAKHS',
      model: 'Mercedes-Benz V-Class',
      pricecount: '₹ 40,000,000',
      mileage: '15.6 km/L',
      variant: 'Diesel',
      engineCc: '1950 cc',
      torque: '380Nm',
      power: '161 bhp',
      seatingCapacity: '7',
      Drivetype: 'RWD',
      NCAPsafetyrating: '5 Star',
      iframeInterior: 'https://example.com/360-view/v-class/interior',
      iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mercedes-Benz/Mercedes-Benz-V-Class/1692872134/Exterior.html?hotSpotNonApp=yes'
    },
    {
      img: './images/seperate/benz/benz4.webp',
      price: 'STARTING FROM 90.2 LAKHS',
      model: 'Mercedes-Benz S-Class',
      pricecount: '₹ 50,000,000',
      mileage: '13.2 km/L',
      variant: 'Petrol',
      engineCc: '2999 cc',
      torque: '520Nm',
      power: '362 bhp',
      seatingCapacity: '5',
      Drivetype: 'RWD',
      NCAPsafetyrating: '5 Star',
      iframeInterior: 'https://example.com/360-view/s-class/interior',
      iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mercedes-Benz/Mercedes-Benz-S-Class/1692872134/Exterior.html?hotSpotNonApp=yes'
    },
    {
      img: './images/seperate/benz/benz4.webp',
      price: 'STARTING FROM 95.8 LAKHS',
      model: 'Mercedes-Benz GLS',
      pricecount: '₹ 55,000,000',
      mileage: '11.9 km/L',
      variant: 'Diesel',
      engineCc: '2925 cc',
      torque: '700Nm',
      power: '325 bhp',
      seatingCapacity: '7',
      Drivetype: 'AWD',
      NCAPsafetyrating: '5 Star',
      iframeInterior: 'https://example.com/360-view/gls/interior',
      iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mercedes-Benz/Mercedes-Benz-GLS/1692872134/Exterior.html?hotSpotNonApp=yes'
    },
    {
      img: './images/seperate/benz/benz4.webp',
      price: 'STARTING FROM 45.8 LAKHS',
      model: 'Mercedes-Benz CLA',
      pricecount: '₹ 22,000,000',
      mileage: '17.6 km/L',
      variant: 'Petrol',
      engineCc: '1991 cc',
      torque: '300Nm',
      power: '221 bhp',
      seatingCapacity: '5',
      Drivetype: 'FWD',
      NCAPsafetyrating: '5 Star',
      iframeInterior: 'https://example.com/360-view/cla/interior',
      iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mercedes-Benz/Mercedes-Benz-CLA/1692872134/Exterior.html?hotSpotNonApp=yes'
    },
      {
        img: './images/seperate/benz/benz4.webp',
        price: 'STARTING FROM 70.2 LAKHS',
        model: 'Mercedes-Benz GLE Coupe',
        pricecount: '₹ 35,000,000',
        mileage: '17.6 km/L',
        variant: 'Diesel',
        engineCc: '1950 cc',
        torque: '400Nm',
        power: '194 bhp',
        seatingCapacity: '5',
        Drivetype: 'AWD',
        NCAPsafetyrating: '5 Star',
        iframeInterior: 'https://example.com/360-view/gle-coupe/interior',
        iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mercedes-Benz/Mercedes-Benz-GLE-Coupe/1692872134/Exterior.html?hotSpotNonApp=yes'
      },
      {
        img: './images/seperate/benz/benz4.webp',
        price: 'STARTING FROM 85.8 LAKHS',
        model: 'Mercedes-Benz S-Class Maestro Edition',
        pricecount: '₹ 40,000,000',
        mileage: '13.5 km/L',
        variant: 'Petrol',
        engineCc: '2996 cc',
        torque: '530Nm',
        power: '362 bhp',
        seatingCapacity: '5',
        Drivetype: 'RWD',
        NCAPsafetyrating: '5 Star',
        iframeInterior: 'https://example.com/360-view/s-class-maestro-edition/interior',
        iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mercedes-Benz/Mercedes-Benz-S-Class-Maestro-Edition/1692872134/Exterior.html?hotSpotNonApp=yes'
      },
      {
        img: './images/seperate/benz/benz3.webp',
        price: 'STARTING FROM 45.6 LAKHS',
        model: 'Mercedes-Benz AMG A 35',
        pricecount: '₹ 20,000,000',
        mileage: '15.8 km/L',
        variant: 'Petrol',
        engineCc: '1991 cc',
        torque: '400Nm',
        power: '302 bhp',
        seatingCapacity: '5',
        Drivetype: 'AWD',
        NCAPsafetyrating: '5 Star',
        iframeInterior: 'https://example.com/360-view/amg-a-35/interior',
        iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mercedes-Benz/Mercedes-Benz-AMG-A-35/1692872134/Exterior.html?hotSpotNonApp=yes'
      },
      {
        img: './images/seperate/benz/benz4.webp',
        price: 'STARTING FROM 65.8 LAKHS',
        model: 'Mercedes-Benz CLS',
        pricecount: '₹ 30,000,000',
        mileage: '16.5 km/L',
        variant: 'Diesel',
        engineCc: '1950 cc',
        torque: '400Nm',
        power: '241 bhp',
        seatingCapacity: '5',
        Drivetype: 'RWD',
        NCAPsafetyrating: '5 Star',
        iframeInterior: 'https://example.com/360-view/cls/interior',
        iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mercedes-Benz/Mercedes-Benz-CLS/1692872134/Exterior.html?hotSpotNonApp=yes'
      },
      {
        img: './images/seperate/benz/benz4.webp',
        price: 'STARTING FROM 55.2 LAKHS',
        model: 'Mercedes-Benz GLC Coupe',
        pricecount: '₹ 25,000,000',
        mileage: '18.9 km/L',
        variant: 'Petrol',
        engineCc: '1991 cc',
        torque: '320Nm',
        power: '242 bhp',
        seatingCapacity: '5',
        Drivetype: 'AWD',
        NCAPsafetyrating: '4 Star',
        iframeInterior: 'https://example.com/360-view/glc-coupe/interior',
        iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mercedes-Benz/Mercedes-Benz-GLC-Coupe/1692872134/Exterior.html?hotSpotNonApp=yes'
      },
      {
        img: './images/seperate/benz/benz2.webp',
        price: 'STARTING FROM 44.8 LAKHS',
        model: 'Mercedes-Benz A-Class Limousine',
        pricecount: '₹ 21,000,000',
        mileage: '20.1 km/L',
        variant: 'Petrol',
        engineCc: '1332 cc',
        torque: '250Nm',
        power: '161 bhp',
        seatingCapacity: '5',
        Drivetype: 'FWD',
        NCAPsafetyrating: '4 Star',
        iframeInterior: 'https://example.com/360-view/a-class-limousine/interior',
        iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mercedes-Benz/Mercedes-Benz-A-Class-Limousine/1692872134/Exterior.html?hotSpotNonApp=yes'
      }
    ];
    
export const bmw = [
  {
    img: './images/seperate/bmw/10.webp',
    price: 'STARTING FROM 70.2 LAKHS',
    model: 'BMW iX',
    pricecount: '₹ 35,000,000',
    mileage: '17.8 km/L',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: '765Nm',
    power: '516 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-iX/Exterior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-iX/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/bmw/9.webp',
    price: 'STARTING FROM 65.5 LAKHS',
    model: 'BMW 5 Series',
    pricecount: '₹ 30,000,000',
    mileage: '15.6 km/L',
    variant: 'Petrol',
    engineCc: '1998 cc',
    torque: '400Nm',
    power: '248 bhp',
    seatingCapacity: '5',
    Drivetype: 'RWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/5-series/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-5-Series/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/bmw/8.webp',
    price: 'STARTING FROM 56.8 LAKHS',
    model: 'BMW X3',
    pricecount: '₹ 28,000,000',
    mileage: '16.3 km/L',
    variant: 'Diesel',
    engineCc: '1998 cc',
    torque: '400Nm',
    power: '187 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X3/1675745866/Exterior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X3/1675745866/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/bmw/7.webp',
    price: 'STARTING FROM 47.2 LAKHS',
    model: 'BMW 3 Series',
    pricecount: '₹ 25,000,000',
    mileage: '15.9 km/L',
    variant: 'Petrol',
    engineCc: '1998 cc',
    torque: '400Nm',
    power: '255 bhp',
    seatingCapacity: '5',
    Drivetype: 'RWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-3-Series/1675685692/Exterior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-3-Series/1675685692/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/bmw/6.webp',
    price: 'STARTING FROM 90.5 LAKHS',
    model: 'BMW i7',
    pricecount: '₹ 45,000,000',
    mileage: '17.2 km/L',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: '880Nm',
    power: '536 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-i7/Exterior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-i7/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/bmw/5.webp',
    price: 'STARTING FROM 78.9 LAKHS',
    model: 'BMW X5',
    pricecount: '₹ 40,000,000',
    mileage: '14.2 km/L',
    variant: 'Diesel',
    engineCc: '2993 cc',
    torque: '620Nm',
    power: '261 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X7/1675749881/Exterior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X5/1708065015/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/bmw/4.webp',
    price: 'STARTING FROM 95.8 LAKHS',
    model: 'BMW XM',
    pricecount: '₹ 50,000,000',
    mileage: '11.9 km/L',
    variant: 'Petrol',
    engineCc: '4395 cc',
    torque: '800Nm',
    power: '625 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X7/1675749881/Exterior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-XM/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/bmw/3.webp',
    price: 'STARTING FROM 40.5 LAKHS',
    model: 'BMW X1',
    pricecount: '₹ 25,000,000',
    mileage: '18.1 km/L',
    variant: 'Petrol',
    engineCc: '1998 cc',
    torque: '280Nm',
    power: '187 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X7/1675749881/Exterior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X1/1677910541/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/bmw/2.webp',
    price: 'STARTING FROM 62.3 LAKHS',
    model: 'BMW Z4',
    pricecount: '₹ 35,000,000',
    mileage: '14.9 km/L',
    variant: 'Petrol',
    engineCc: '2998 cc',
    torque: '500Nm',
    power: '254 bhp',
    seatingCapacity: '2',
    Drivetype: 'RWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X7/1675749881/Exterior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X1/1677910541/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/bmw/1.webp',
    price: 'STARTING FROM 80.2 LAKHS',
    model: 'BMW X7',
    pricecount: '₹ 45,000,000',
    mileage: '12.6 km/L',
    variant: 'Diesel',
    engineCc: '2993 cc',
    torque: '700Nm',
    power: '335 bhp',
    seatingCapacity: '7',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X7/1675749881/Exterior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/BMW/BMW-X1/1677910541/Exterior.html?hotSpotNonApp=yes'
  }
];
export const tata = [
  {
    img: './images/seperate/tata/tigor_ev.webp',
    price: 'STARTING FROM 11.2 LAKHS',
    model: 'Tata Tigor EV',
    pricecount: '₹ 10,000,000',
    mileage: '306 km/charge',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: '170Nm',
    power: '74 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tiago-EV/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Tigor/1630496142/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/tata/tigor.webp',
    price: 'STARTING FROM 6.5 LAKHS',
    model: 'Tata Tigor',
    pricecount: '₹ 6,000,000',
    mileage: '20.3 km/L',
    variant: 'Petrol',
    engineCc: '1199 cc',
    torque: '113Nm',
    power: '84 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tigor/1609827993/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Tigor/1630496142/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/tata/tiago_ev.webp',
    price: 'STARTING FROM 9.8 LAKHS',
    model: 'Tata Tiago EV',
    pricecount: '₹ 9,000,000',
    mileage: '306 km/charge',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: '140Nm',
    power: '86 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tiago-EV/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Tiago-EV/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/tata/nexon_ev.webp',
    price: 'STARTING FROM 14.2 LAKHS',
    model: 'Tata Nexon EV',
    pricecount: '₹ 13,000,000',
    mileage: '312 km/charge',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: '245Nm',
    power: '127 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tiago-EV/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Nexon-EV/1697705255/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/tata/altroz.webp',
    price: 'STARTING FROM 7.2 LAKHS',
    model: 'Tata Altroz',
    pricecount: '₹ 7,000,000',
    mileage: '25.11 km/L',
    variant: 'Petrol',
    engineCc: '1199 cc',
    torque: '113Nm',
    power: '85 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tiago-EV/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Altroz/1692872134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/tata/tiago.webp',
    price: 'STARTING FROM 5.5 LAKHS',
    model: 'Tata Tiago',
    pricecount: '₹ 5,000,000',
    mileage: '23.84 km/L',
    variant: 'Petrol',
    engineCc: '1199 cc',
    torque: '113Nm',
    power: '84 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tiago-EV/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Nexon-EV/1697705255/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/tata/safari.webp',
    price: 'STARTING FROM 15.5 LAKHS',
    model: 'Tata Safari',
    pricecount: '₹ 15,000,000',
    mileage: '16.14 km/L',
    variant: 'Diesel',
    engineCc: '1956 cc',
    torque: '350Nm',
    power: '168 bhp',
    seatingCapacity: '6/7',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tiago-EV/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Safari/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/tata/punch_ev.webp',
    price: 'STARTING FROM 8.2 LAKHS',
    model: 'Tata Punch EV',
    pricecount: '₹ 8,000,000',
    mileage: 'N/A',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: 'N/A',
    power: 'N/A',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: 'N/A',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tiago-EV/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Punch-EV/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/tata/harrier.webp',
    price: 'STARTING FROM 16.8 LAKHS',
    model: 'Tata Harrier',
    pricecount: '₹ 16,000,000',
    mileage: '16.35 km/L',
    variant: 'Diesel',
    engineCc: '1956 cc',
    torque: '350Nm',
    power: '168 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tiago-EV/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Harrier/1702960134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/tata/nexon.webp',
    price: 'STARTING FROM 8.5 LAKHS',
    model: 'Tata Nexon',
    pricecount: '₹ 8,000,000',
    mileage: '22.4 km/L',
    variant: 'Petrol',
    engineCc: '1199 cc',
    torque: '170Nm',
    power: '118 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Tata/Tata-Tiago-EV/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Tata/Tata-Nexon/1702960134/Exterior.html?hotSpotNonApp=yes'
  }
];

export const landRover = [
  {
    img: './images/seperate/landrover/eq.webp',
    price: 'STARTING FROM 67.2 LAKHS',
    model: 'Land Rover Range Rover Evoque',
    pricecount: '₹ 65,000,000',
    mileage: '15.68 km/L',
    variant: 'Petrol',
    engineCc: '1997 cc',
    torque: '365Nm',
    power: '246 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/evoque/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Land-Rover/Land-Rover-Range-Rover-Evoque/1692872134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/landrover/sports.webp',
    price: 'STARTING FROM 89.5 LAKHS',
    model: 'Land Rover Range Rover Sport',
    pricecount: '₹ 85,000,000',
    mileage: '13.33 km/L',
    variant: 'Diesel',
    engineCc: '2993 cc',
    torque: '650Nm',
    power: '296 bhp',
    seatingCapacity: '5/7',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/sport/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Land-Rover/Land-Rover-Range-Rover-Sport/1653567357/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/landrover/range-rover-velar.webp',
    price: 'STARTING FROM 80.8 LAKHS',
    model: 'Land Rover Range Rover Velar',
    pricecount: '₹ 75,000,000',
    mileage: '16.4 km/L',
    variant: 'Diesel',
    engineCc: '1997 cc',
    torque: '430Nm',
    power: '246 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/velar/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Land-Rover/Land-Rover-Range-Rover-Velar/1692872134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/landrover/rangerover.webp',
    price: 'STARTING FROM 105.2 LAKHS',
    model: 'Land Rover Range Rover',
    pricecount: '₹ 100,000,000',
    mileage: '12.8 km/L',
    variant: 'Diesel',
    engineCc: '2993 cc',
    torque: '650Nm',
    power: '296 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/range-rover/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Land-Rover/Land-Rover-Range-Rover/1676525435/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/landrover/defender.webp',
    price: 'STARTING FROM 76.5 LAKHS',
    model: 'Land Rover Defender',
    pricecount: '₹ 70,000,000',
    mileage: '14.5 km/L',
    variant: 'Diesel',
    engineCc: '1999 cc',
    torque: '430Nm',
    power: '296 bhp',
    seatingCapacity: '5/6/7',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/defender/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Land-Rover/Land-Rover-Defender/Exterior.html?hotSpotNonApp=yes'
  }
];
export const marutiSuzuki = [
  {
    img: './images/seperate/marutisuzuki/wag.webp',
    price: 'STARTING FROM 9.2 LAKHS',
    model: 'Maruti Suzuki Ciaz',
    pricecount: '₹ 9,000,000',
    mileage: '20.65 km/L',
    variant: 'Petrol',
    engineCc: '1462 cc',
    torque: '138Nm',
    power: '103 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Maruti/Maruti-Swift-Dzire/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Maruti-Suzuki/Maruti-Suzuki-Ciaz/1692872134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/marutisuzuki/tor.webp',
    price: 'STARTING FROM 8.5 LAKHS',
    model: 'Maruti Suzuki Ertiga',
    pricecount: '₹ 8,000,000',
    mileage: '19.01 km/L',
    variant: 'Petrol',
    engineCc: '1462 cc',
    torque: '138Nm',
    power: '103 bhp',
    seatingCapacity: '7',
    Drivetype: 'FWD',
    NCAPsafetyrating: '3 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Maruti/Maruti-Swift-Dzire/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Maruti-Suzuki/Maruti-Suzuki-Ertiga/1692872134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/marutisuzuki/pres.webp',
    price: 'STARTING FROM 8.9 LAKHS',
    model: 'Maruti Suzuki Vitara Brezza',
    pricecount: '₹ 8,500,000',
    mileage: '17.03 km/L',
    variant: 'Petrol',
    engineCc: '1462 cc',
    torque: '138Nm',
    power: '103 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Maruti/Maruti-Swift-Dzire/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Maruti-Suzuki/Maruti-Suzuki-Vitara-Brezza/1692872134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/marutisuzuki/dzire.webp',
    price: 'STARTING FROM 5.2 LAKHS',
    model: 'Maruti Suzuki Wagon R',
    pricecount: '₹ 5,000,000',
    mileage: '21.79 km/L',
    variant: 'Petrol',
    engineCc: '998 cc',
    torque: '90Nm',
    power: '67 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '3 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Maruti/Maruti-Swift-Dzire/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Maruti-Suzuki/Maruti-Suzuki-Wagon-R/1692872134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/marutisuzuki/not.webp',
    price: 'STARTING FROM 6.5 LAKHS',
    model: 'Maruti Suzuki Baleno',
    pricecount: '₹ 6,000,000',
    mileage: '23.87 km/L',
    variant: 'Petrol',
    engineCc: '1197 cc',
    torque: '113Nm',
    power: '82 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '3 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Maruti/Maruti-Swift-Dzire/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Maruti-Suzuki/Maruti-Suzuki-Baleno/1692872134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/marutisuzuki/dzire.webp',
    price: 'STARTING FROM 6.0 LAKHS',
    model: 'Maruti Suzuki Dzire',
    pricecount: '₹ 5,800,000',
    mileage: '24.12 km/L',
    variant: 'Petrol',
    engineCc: '1197 cc',
    torque: '113Nm',
    power: '82 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '3 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Maruti/Maruti-Swift-Dzire/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Maruti/Maruti-Swift-Dzire/1597904089/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/marutisuzuki/swift.webp',
    price: 'STARTING FROM 5.9 LAKHS',
    model: 'Maruti Suzuki Swift',
    pricecount: '₹ 5,700,000',
    mileage: '23.2 km/L',
    variant: 'Petrol',
    engineCc: '1197 cc',
    torque: '113Nm',
    power: '82 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '2 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Maruti/Maruti-Swift/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Maruti/Maruti-Swift/1622112037/Exterior.html?hotSpotNonApp=yes'
  }
];

export const volkswagen = [
  {
    img: './images/seperate/volkswagen/polo.webp',
    price: 'STARTING FROM 10.2 LAKHS',
    model: 'Volkswagen Polo GT',
    pricecount: '₹ 10,000,000',
    mileage: '17.21 km/L',
    variant: 'Petrol',
    engineCc: '999 cc',
    torque: '175Nm',
    power: '108 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '3 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Volkswagen/Volkswagen-Polo/1576500560 /Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Volkswagen/Volkswagen-Virtus/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/volkswagen/vento.webp',
    price: 'STARTING FROM 31.5 LAKHS',
    model: 'Volkswagen Tiguan',
    pricecount: '₹ 30,000,000',
    mileage: '16.65 km/L',
    variant: 'Diesel',
    engineCc: '1968 cc',
    torque: '340Nm',
    power: '148 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Volkswagen/Volkswagen-Polo/1576500560 /Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Volkswagen/Volkswagen-Virtus/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/volkswagen/virtus.webp',
    price: 'STARTING FROM 21.9 LAKHS',
    model: 'Volkswagen T-Roc',
    pricecount: '₹ 20,000,000',
    mileage: '17.85 km/L',
    variant: 'Petrol',
    engineCc: '1498 cc',
    torque: '250Nm',
    power: '148 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Volkswagen/Volkswagen-Polo/1576500560 /Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Volkswagen/Volkswagen-Virtus/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/volkswagen/polo.webp',
    price: 'STARTING FROM 10.5 LAKHS',
    model: 'Volkswagen Taigun',
    pricecount: '₹ 10,000,000',
    mileage: '18.57 km/L',
    variant: 'Petrol',
    engineCc: '999 cc',
    torque: '175Nm',
    power: '108 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Volkswagen/Volkswagen-Polo/1576500560 /Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Volkswagen/Volkswagen-Virtus/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/volkswagen/vento.webp',
    price: 'STARTING FROM 10.0 LAKHS',
    model: 'Volkswagen Vento',
    pricecount: '₹ 9,500,000',
    mileage: '17.69 km/L',
    variant: 'Petrol',
    engineCc: '999 cc',
    torque: '175Nm',
    power: '108 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Volkswagen/Volkswagen-Polo/1576500560 /Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Volkswagen/Volkswagen-Virtus/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/volkswagen/polo.webp',
    price: 'STARTING FROM 6.5 LAKHS',
    model: 'Volkswagen Polo',
    pricecount: '₹ 6,000,000',
    mileage: '18.24 km/L',
    variant: 'Petrol',
    engineCc: '999 cc',
    torque: '175Nm',
    power: '75 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '3 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Volkswagen/Volkswagen-Polo/1576500560 /Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Volkswagen/Volkswagen-Virtus/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/volkswagen/virtus.webp',
    price: 'STARTING FROM 10.0 LAKHS',
    model: 'Volkswagen Virtus',
    pricecount: '₹ 9,500,000',
    mileage: '17.69 km/L',
    variant: 'Petrol',
    engineCc: '999 cc',
    torque: '175Nm',
    power: '108 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Volkswagen/Volkswagen-Polo/1576500560 /Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Volkswagen/Volkswagen-Virtus/Exterior.html?hotSpotNonApp=yes'
  }
];
export const mahindra = [
  {
    img: './images/seperate/mahindra/bolero_neo.webp',
    price: 'STARTING FROM 8.2 LAKHS',
    model: 'Mahindra Bolero Pik-Up',
    pricecount: '₹ 8,000,000',
    mileage: '16.7 km/L',
    variant: 'Diesel',
    engineCc: '1493 cc',
    torque: '260Nm',
    power: '75 bhp',
    seatingCapacity: '2/5',
    Drivetype: 'RWD',
    NCAPsafetyrating: 'Not Rated',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Mahindra/Mahindra-XUV700/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mahindra/Mahindra-XUV700/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/mahindra/xuv400_ev.webp',
    price: 'STARTING FROM 9.5 LAKHS',
    model: 'Mahindra E Verito',
    pricecount: '₹ 9,000,000',
    mileage: '181 km/charge',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: 'N/A',
    power: '41 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: 'Not Rated',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Mahindra/Mahindra-XUV700/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mahindra/Mahindra-XUV700/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/mahindra/marazzo.webp',
    price: 'STARTING FROM 12.5 LAKHS',
    model: 'Mahindra Marazzo',
    pricecount: '₹ 12,000,000',
    mileage: '17.3 km/L',
    variant: 'Diesel',
    engineCc: '1497 cc',
    torque: '300Nm',
    power: '120 bhp',
    seatingCapacity: '7/8',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Mahindra/Mahindra-XUV700/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mahindra/Mahindra-XUV700/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/mahindra/alturas_g4.webp',
    price: 'STARTING FROM 30.0 LAKHS',
    model: 'Mahindra Alturas G4',
    pricecount: '₹ 30,000,000',
    mileage: '12.05 km/L',
    variant: 'Diesel',
    engineCc: '2157 cc',
    torque: '450Nm',
    power: '178 bhp',
    seatingCapacity: '7',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Mahindra/Mahindra-XUV700/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mahindra/Mahindra-XUV700/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/mahindra/bolero_neo.webp',
    price: 'STARTING FROM 9.6 LAKHS',
    model: 'Mahindra Bolero Neo',
    pricecount: '₹ 9,500,000',
    mileage: '16.7 km/L',
    variant: 'Diesel',
    engineCc: '1493 cc',
    torque: '260Nm',
    power: '75 bhp',
    seatingCapacity: '5/7',
    Drivetype: 'RWD',
    NCAPsafetyrating: 'Not Rated',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Mahindra/Mahindra-XUV700/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mahindra/Mahindra-XUV700/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/mahindra/xuv300.webp',
    price: 'STARTING FROM 8.3 LAKHS',
    model: 'Mahindra XUV300',
    pricecount: '₹ 8,000,000',
    mileage: '20.0 km/L',
    variant: 'Petrol / Diesel',
    engineCc: '1197 / 1497 cc',
    torque: '200 / 300Nm',
    power: '108 / 115 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Mahindra/Mahindra-XUV700/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mahindra/Mahindra-XUV700/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/mahindra/scorpio.webp',
    price: 'STARTING FROM 11.9 LAKHS',
    model: 'Mahindra Scorpio',
    pricecount: '₹ 11,500,000',
    mileage: '15.4 km/L',
    variant: 'Diesel',
    engineCc: '2179 cc',
    torque: '320Nm',
    power: '140 bhp',
    seatingCapacity: '7/9',
    Drivetype: 'RWD / 4WD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Mahindra/Mahindra-XUV700/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mahindra/Mahindra-XUV700/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/mahindra/thar.webp',
    price: 'STARTING FROM 12.8 LAKHS',
    model: 'Mahindra Thar',
    pricecount: '₹ 12,500,000',
    mileage: '15.2 km/L',
    variant: 'Petrol / Diesel',
    engineCc: '1997 / 2184 cc',
    torque: '320 / 300Nm',
    power: '150 / 130 bhp',
    seatingCapacity: '4/6',
    Drivetype: '4WD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Mahindra/Mahindra-XUV700/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mahindra/Mahindra-Thar/1620980352/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/mahindra/xuv700.webp',
    price: 'STARTING FROM 12.5 LAKHS',
    model: 'Mahindra XUV700',
    pricecount: '₹ 12,000,000',
    mileage: '15.0 km/L',
    variant: 'Petrol / Diesel',
    engineCc: '1989 / 1997 cc',
    torque: '380 / 450Nm',
    power: '200 / 185 bhp',
    seatingCapacity: '6/7',
    Drivetype: 'FWD / AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/Mahindra/Mahindra-XUV700/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Mahindra/Mahindra-XUV700/Exterior.html?hotSpotNonApp=yes'
  }
];

export const morrisGarage = [
  {
    img: './images/seperate/morrisgarage/ev.webp',
    price: 'STARTING FROM 12.5 LAKHS',
    model: 'Morris Garage ZS',
    pricecount: '₹ 12,000,000',
    mileage: '17.5 km/L',
    variant: 'Petrol',
    engineCc: '1498 cc',
    torque: '150Nm',
    power: '105 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/MG/MG-Hector/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/MG/MG-Hector/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/morrisgarage/astor.webp',
    price: 'STARTING FROM 10.9 LAKHS',
    model: 'Morris Garage Astor',
    pricecount: '₹ 10,500,000',
    mileage: '18.3 km/L',
    variant: 'Petrol',
    engineCc: '1399 cc',
    torque: '220Nm',
    power: '140 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/MG/MG-Hector/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/MG/MG-Hector/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/morrisgarage/hector_plus.webp',
    price: 'STARTING FROM 14.0 LAKHS',
    model: 'Morris Garage Hector Plus',
    pricecount: '₹ 14,000,000',
    mileage: '16.56 km/L',
    variant: 'Diesel',
    engineCc: '1956 cc',
    torque: '350Nm',
    power: '168 bhp',
    seatingCapacity: '6/7',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/MG/MG-Hector/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/MG/MG-Hector/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/morrisgarage/zs_ev.webp',
    price: 'STARTING FROM 21.0 LAKHS',
    model: 'Morris Garage ZS EV',
    pricecount: '₹ 21,000,000',
    mileage: '340 km/full charge',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: 'N/A',
    power: '141 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/MG/MG-Hector/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/MG/MG-Hector/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/morrisgarage/gloster.webp',
    price: 'STARTING FROM 31.0 LAKHS',
    model: 'Morris Garage Gloster',
    pricecount: '₹ 31,000,000',
    mileage: '12.6 km/L',
    variant: 'Diesel',
    engineCc: '1996 cc',
    torque: '480Nm',
    power: '215 bhp',
    seatingCapacity: '6/7',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/MG/MG-Hector/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/MG/MG-Hector/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/morrisgarage/hector.webp',
    price: 'STARTING FROM 14.0 LAKHS',
    model: 'Morris Garage Hector',
    pricecount: '₹ 14,000,000',
    mileage: '15.81 km/L',
    variant: 'Petrol / Diesel / Hybrid',
    engineCc: '1451 / 1956 cc',
    torque: '250 / 350Nm',
    power: '141 / 168 bhp',
    seatingCapacity: '5/6/7',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://stimg.cardekho.com/images/feelthecar360view/Interior/MG/MG-Hector/Interior.html?hotSpotNonApp=yes',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/MG/MG-Hector/Exterior.html?hotSpotNonApp=yes'
  }
];

export const jaguar = [
  {
    img: './images/seperate/jaguar/i_pace.webp',
    price: 'STARTING FROM 69.9 LAKHS',
    model: 'Jaguar I-PACE',
    pricecount: '₹ 69,900,000',
    mileage: '470 km/full charge',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: '696Nm',
    power: '394 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/i-pace/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Jaguar/Jaguar-F-Pace/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/jaguar/i_pace.webp',
    price: 'STARTING FROM 56.4 LAKHS',
    model: 'Jaguar E-PACE',
    pricecount: '₹ 56,400,000',
    mileage: '15.2 km/L',
    variant: 'Petrol',
    engineCc: '1997 cc',
    torque: '365Nm',
    power: '246 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/e-pace/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Jaguar/Jaguar-F-Pace/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/jaguar/f_pace.webp',
    price: 'STARTING FROM 69.9 LAKHS',
    model: 'Jaguar F-PACE',
    pricecount: '₹ 69,900,000',
    mileage: '14.5 km/L',
    variant: 'Diesel',
    engineCc: '1997 cc',
    torque: '365Nm',
    power: '246 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/f-pace/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Jaguar/Jaguar-F-Pace/Exterior.html?hotSpotNonApp=yes'
  }
];
export const volvo = [
  {
    img: './images/seperate/volvo/xc40.webp',
    price: 'STARTING FROM 41.25 LAKHS',
    model: 'Volvo XC60',
    pricecount: '₹ 41,250,000',
    mileage: '18.0 km/L',
    variant: 'Petrol / Diesel',
    engineCc: '1969 cc',
    torque: '300Nm',
    power: '190 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/xc40/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Volvo/Volvo-XC40/1692872134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/volvo/xc90.webp',
    price: 'STARTING FROM 45.9 LAKHS',
    model: 'Volvo S60',
    pricecount: '₹ 45,900,000',
    mileage: '16.8 km/L',
    variant: 'Petrol / Hybrid',
    engineCc: '1969 / 1969 cc',
    torque: '300 / 350Nm',
    power: '190 / 303 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD / AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/s60/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Volvo/Volvo-S60/1692872134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/volvo/xc60.webp',
    price: 'STARTING FROM 60.9 LAKHS',
    model: 'Volvo XC60',
    pricecount: '₹ 60,900,000',
    mileage: '11.2 km/L',
    variant: 'Petrol / Diesel',
    engineCc: '1969 / 1969 cc',
    torque: '350 / 420Nm',
    power: '250 / 235 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/xc60/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Volvo/Volvo-XC60/1692872134/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/volvo/xc90.webp',
    price: 'STARTING FROM 89.9 LAKHS',
    model: 'Volvo XC90',
    pricecount: '₹ 89,900,000',
    mileage: '42.0 km/L',
    variant: 'Petrol / Hybrid',
    engineCc: '1969 / 1969 cc',
    torque: '300 / 350Nm',
    power: '190 / 303 bhp',
    seatingCapacity: '6/7',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/xc90/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Volvo/Volvo-XC90/1692872134/Exterior.html?hotSpotNonApp=yes'
  }
];

export const skoda = [
  {
    img: './images/seperate/skoda/kushaq.webp',
    price: 'STARTING FROM 10.5 LAKHS',
    model: 'Skoda Kushaq',
    pricecount: '₹ 10,500,000',
    mileage: '17.88 km/L',
    variant: 'Petrol / Diesel',
    engineCc: '999 / 1498 cc',
    torque: '175 / 250Nm',
    power: '115 / 113 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/kushaq/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Skoda/Skoda-Kushaq/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/skoda/rapid.webp',
    price: 'STARTING FROM 8.2 LAKHS',
    model: 'Skoda Rapid',
    pricecount: '₹ 8,200,000',
    mileage: '18.97 km/L',
    variant: 'Petrol / Diesel',
    engineCc: '999 / 1498 cc',
    torque: '175 / 250Nm',
    power: '110 / 113 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://example.com/360-view/rapid/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Skoda/Skoda-Kushaq/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/skoda/octavia.webp',
    price: 'STARTING FROM 26.0 LAKHS',
    model: 'Skoda Octavia',
    pricecount: '₹ 26,000,000',
    mileage: '15.81 km/L',
    variant: 'Petrol',
    engineCc: '1984 cc',
    torque: '320Nm',
    power: '187 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/octavia/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Skoda/Skoda-Kushaq/Exterior.html?hotSpotNonApp=yes'
  }
];
export const kia = [
  {
    img: './images/seperate/kia/carens.webp',
    price: 'STARTING FROM 10.5 LAKHS',
    model: 'Kia Carens',
    pricecount: '₹ 10,500,000',
    mileage: '18.5 km/L',
    variant: 'Petrol / Diesel',
    engineCc: '1497 / 1493 cc',
    torque: '144 / 250Nm',
    power: '113 / 113 bhp',
    seatingCapacity: '6/7',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://example.com/360-view/carens/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Kia/Kia-EV6/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/kia/Kia Seltos EV.webp',
    price: 'STARTING FROM 18.2 LAKHS',
    model: 'Kia Seltos EV',
    pricecount: '₹ 18,200,000',
    mileage: '450 km/full charge',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: 'N/A',
    power: '201 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/seltos-ev/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Kia/Kia-EV6/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/kia/carnival.webp',
    price: 'STARTING FROM 24.0 LAKHS',
    model: 'Kia Carnival',
    pricecount: '₹ 24,000,000',
    mileage: '13.9 km/L',
    variant: 'Diesel',
    engineCc: '2199 cc',
    torque: '440Nm',
    power: '197 bhp',
    seatingCapacity: '7/8',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/carnival/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Kia/Kia-Seltos/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/kia/sonet.webp',
    price: 'STARTING FROM 6.8 LAKHS',
    model: 'Kia Sonet',
    pricecount: '₹ 6,800,000',
    mileage: '24.1 km/L',
    variant: 'Petrol / Diesel',
    engineCc: '998 / 1493 cc',
    torque: '172 / 250Nm',
    power: '118 / 113 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '4 Star',
    iframeInterior: 'https://example.com/360-view/sonet/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Kia/Kia-Seltos/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/kia/seltos.webp',
    price: 'STARTING FROM 9.9 LAKHS',
    model: 'Kia Seltos',
    pricecount: '₹ 9,900,000',
    mileage: '16.1 km/L',
    variant: 'Petrol / Diesel',
    engineCc: '1497 / 1493 cc',
    torque: '144 / 250Nm',
    power: '113 / 113 bhp',
    seatingCapacity: '5',
    Drivetype: 'FWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/seltos/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Kia/Kia-Seltos/Exterior.html?hotSpotNonApp=yes'
  }
];
export const porschee = [
  {
    img: './images/seperate/porsche/911.webp',
    price: 'STARTING FROM 85.0 LAKHS',
    model: 'Porsche 718 Cayman',
    pricecount: '₹ 85,000,000',
    mileage: '13.8 km/L',
    variant: 'Petrol',
    engineCc: '1988 cc',
    torque: '420Nm',
    power: '295 bhp',
    seatingCapacity: '2',
    Drivetype: 'RWD',
    NCAPsafetyrating: 'Not Rated',
    iframeInterior: 'https://example.com/360-view/718-cayman/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Porsche/Porsche-Taycan/1677666193/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/porsche/taycan.webp',
    price: 'STARTING FROM 1.50 CRORES',
    model: 'Porsche Taycan',
    pricecount: '₹ 1,50,00,000',
    mileage: '420 km/full charge',
    variant: 'Electric',
    engineCc: 'N/A',
    torque: 'N/A',
    power: '469 bhp',
    seatingCapacity: '4/5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/taycan/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Porsche/Porsche-Taycan/1677666193/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/porsche/macan.webp',
    price: 'STARTING FROM 70.0 LAKHS',
    model: 'Porsche Macan',
    pricecount: '₹ 70,000,000',
    mileage: '11.23 km/L',
    variant: 'Petrol',
    engineCc: '1984 cc',
    torque: '430Nm',
    power: '248 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: '5 Star',
    iframeInterior: 'https://example.com/360-view/macan/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Porsche/Porsche-Macan/1677654929/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/porsche/cayenne.webp',
    price: 'STARTING FROM 1.20 CRORES',
    model: 'Porsche Cayenne',
    pricecount: '₹ 1,20,00,000',
    mileage: '9.6 km/L',
    variant: 'Petrol / Hybrid',
    engineCc: '2995 / 2995 cc',
    torque: '450 / 700Nm',
    power: '335 / 460 bhp',
    seatingCapacity: '5',
    Drivetype: 'AWD',
    NCAPsafetyrating: 'Not Rated',
    iframeInterior: 'https://example.com/360-view/cayenne/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Porsche/Porsche-Cayenne/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/porsche/panmera.webp',
    price: 'STARTING FROM 1.50 CRORES',
    model: 'Porsche Panamera',
    pricecount: '₹ 1,50,00,000',
    mileage: '14.7 km/L',
    variant: 'Petrol / Hybrid',
    engineCc: '2995 / 2894 cc',
    torque: '450 / 700Nm',
    power: '335 / 456 bhp',
    seatingCapacity: '4/5',
    Drivetype: 'AWD',
    NCAPsafetyrating: 'Not Rated',
    iframeInterior: 'https://example.com/360-view/panamera/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Porsche/Porsche-Panamera/Exterior.html?hotSpotNonApp=yes'
  },
  {
    img: './images/seperate/porsche/911.webp',
    price: 'STARTING FROM 2.20 CRORES',
    model: 'Porsche 911',
    pricecount: '₹ 2,20,00,000',
    mileage: '8.0 km/L',
    variant: 'Petrol',
    engineCc: '3745 cc',
    torque: '530Nm',
    power: '444 bhp',
    seatingCapacity: '4',
    Drivetype: 'RWD',
    NCAPsafetyrating: 'Not Rated',
    iframeInterior: 'https://example.com/360-view/911/interior',
    iframeExterior: 'https://stimg.cardekho.com/images/feelthecar360view/Exterior/Porsche/Porsche-911/1623734594/Exterior.html?hotSpotNonApp=yes'
  }
];
